[hyprwatermark]

description = "A Hyprland plugin that adds customizable image watermarks inside application windows."

authors = ["Arindam Langer"]

output = "hyprwatermark.so"

build = [
    "make"
]
